### ISSUE TITLE
Implement distance modes

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_VL53L1X_Arduino_Library#2]
Section 2.5.1 in datasheet

**Comment by artlyra** [comment]
It would also be great to implement a way of programming the ROI, according to the datasheet:
"ROI size and position are programmable: the user may chose a custom FoV from 4x4 SPADs (minimum size) up to 16x16 SPADs (full FoV). " This means the sensor could have a FOV angle as narrow as 15 deg.

**Comment by nseidle** [comment]
Thanks @artlyra - to keep things straight please consider starting a new issue for a new feature request

**Comment by AndyEngland521** [comment]
ROI functions have been added in new version.
