### ISSUE TITLE
Default argument after previous specification in header

### ISSUE THREAD

**Issue by matthias-mueller** [sparkfun/SparkFun_VL53L1X_Arduino_Library#22]
https://github.com/sparkfun/SparkFun_VL53L1X_Arduino_Library/blob/1773c55cb9fe2427d5f6ceef2aaf080b380fc88f/src/SparkFun_VL53L1X.cpp#L6

The first argument should not have a default value (that has been already declared in header file).
Fix:
```c
SFEVL53L1X::SFEVL53L1X(TwoWire &i2cPort, int shutdownPin, int interruptPin)
```

**Comment by AndyEngland521** [comment]
Good catch, fixed and pushed, check out v1.1.1
