### ISSUE TITLE
return value of begin() is incompatible

### ISSUE THREAD

**Issue by iZhangHui** [sparkfun/SparkFun_VL53L1X_Arduino_Library#25]
In general, the return value of [begin()](https://github.com/sparkfun/SparkFun_VL53L1X_Arduino_Library/blob/6ff677cc15f8f0c6c289fdc85ab19140c4baa722/examples/Example1_ReadDistance/Example1_ReadDistance.ino#L40) is true when sensor is initilized successfully.

**Comment by AndyEngland521** [comment]
Fixed in v1.1.5

**Comment by AndyEngland521** [comment]
Thanks for the catch!
