### ISSUE TITLE
Possibility to add custom Regions of interests?

### ISSUE THREAD

**Issue by burton666** [sparkfun/SparkFun_VL53L1X_Arduino_Library#26]
When I looked at the official documentation from ST it looks like you can define custom areas to be checked separately. From my limited understanding when looking at this library it is just possible to define how narrow the fov should be from the center. I would like the possibility to define two zones left-right so you can check for movement and also direction of movement.

**Comment by AndyEngland521** [comment]
Updated setROI to include the ability to set an optical center in v1.2.0
