### ISSUE TITLE
Error in read distance example

### ISSUE THREAD

**Issue by DanRosenfeld** [sparkfun/SparkFun_VL53L1X_Arduino_Library#28]
Pretty sure the following line in the ReadDistance example

` if (distanceSensor.begin() == true)`

should read 

`if (distanceSensor.begin() == false)`

since begin() returns 0 on success.

**Comment by AndyEngland521** [comment]
Nice catch @DanRosenfeld I think I'll change it to == 0 so it isn't as confusing

**Comment by AndyEngland521** [comment]
Fixed in v1.1.6, Thanks!

**Comment by DanRosenfeld** [comment]
Super--glad to help.
