### ISSUE TITLE
exit VL53L1X_SensorInit() after timeout if no sensor / sensor doesn't work

### ISSUE THREAD

**Issue by zwerfl** [sparkfun/SparkFun_VL53L1X_Arduino_Library#29]
if there is no sensor connected the initialisation gets stuck in the while-loop inside of VL53L1X_ERROR VL53L1X::VL53L1X_SensorInit();
proposal is to add a timeout, so that the init() function returns to the calling program with a defined error code after a second or so

**Comment by AndyEngland521** [comment]
Added feature in v1.2.3, thanks @zwerfl

**Comment by zwerfl** [comment]
@ AndyEngland521: thanks for considering, and more important: many thanks for developing and providing this great lib!!!
